"""Export the LearnableFFT 1D detector to firmware/wingbeat_lfft/model_lfft.h.

Model (0.913 accuracy): LearnableFFT(48 filters, k=129, stride=4, pad=64,
bias=False) -> magnitude -> Conv1d(48->32,k5)+BN+ReLU+Pool -> Conv1d(32->32,k3)
+BN+ReLU+Pool -> GAP -> Linear(32->2).

FFT conv weights are emitted raw (no BN); the two conv blocks have BN folded in.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from scripts.improve_audio_detector_1d import LFFTDetector  # noqa: E402

CKPT = ROOT / "experiments" / "exp_audio_detector_1d_improved" / "best.pt"
STREAM = ROOT / "experiments" / "exp_audio_detector_1d" / "stream_test.npz"
OUT = ROOT / "firmware" / "wingbeat_lfft" / "model_lfft.h"


def fold_bn(conv, bn):
    w = conv.weight.detach().cpu().numpy()
    b = (conv.bias.detach().cpu().numpy() if conv.bias is not None
         else np.zeros(w.shape[0], np.float32))
    g = bn.weight.detach().cpu().numpy(); beta = bn.bias.detach().cpu().numpy()
    mean = bn.running_mean.detach().cpu().numpy(); var = bn.running_var.detach().cpu().numpy()
    scale = g / np.sqrt(var + bn.eps)
    return (w * scale[:, None, None]).astype(np.float32), (beta + scale * (b - mean)).astype(np.float32)


def emit(name, arr, fmt="{:.7g}f"):
    flat = arr.flatten()
    body = ",\n  ".join(", ".join(fmt.format(float(x)) for x in flat[i:i+8]) for i in range(0, len(flat), 8))
    return f"static const float {name}[{len(flat)}] = {{\n  {body}\n}};\n"


def main() -> int:
    ck = torch.load(CKPT, map_location="cpu", weights_only=False)
    classes = ck["classes"]
    m = LFFTDetector(n_filters=48).eval(); m.load_state_dict(ck["model"])
    print(f"== {sum(p.numel() for p in m.parameters()):,} params, classes {classes}")

    fft_w = m.fft.conv.weight.detach().cpu().numpy().astype(np.float32)  # (96,1,129)
    fft_w = fft_w[:, 0, :]  # (96,129)
    eps = float(m.fft.eps)
    b1_w, b1_b = fold_bn(m.b1[0], m.b1[1])   # (32,48,5), (32,)
    b2_w, b2_b = fold_bn(m.b2[0], m.b2[1])   # (32,32,3), (32,)
    fc_w = m.fc.weight.detach().cpu().numpy().astype(np.float32)  # (2,32)
    fc_b = m.fc.bias.detach().cpu().numpy().astype(np.float32)

    # reference samples
    z = np.load(STREAM, allow_pickle=True)
    X, y = z["X"], z["y"]
    rng = np.random.default_rng(42); idx = []
    for c in range(len(classes)):
        ci = np.where(y == c)[0]
        idx.extend(int(i) for i in rng.choice(ci, size=min(3, len(ci)), replace=False))
    sX = X[idx].astype(np.float32); sY = y[idx].astype(np.int64)
    with torch.no_grad():
        logits = m(torch.as_tensor(sX).unsqueeze(1)).numpy()
        preds = logits.argmax(-1)
    print(f"   ref preds {preds.tolist()} vs true {sY.tolist()}")

    NC = len(classes)
    p = []
    p.append("// AUTO-GENERATED by scripts/export_lfft_for_esp32.py — do not edit\n#pragma once\n\n")
    p.append("// LearnableFFT detector: FFT(48,k129,s4,p64) -> |.| -> Conv(48->32,k5)+Pool -> Conv(32->32,k3)+Pool -> GAP -> FC(32,2)\n\n")
    p.append(f"#define MODEL_INPUT_LEN {sX.shape[1]}\n#define MODEL_N_CLASSES {NC}\n")
    p.append("#define FFT_N_FILT 48\n#define FFT_KERNEL 129\n#define FFT_STRIDE 4\n#define FFT_PAD 64\n#define FFT_T 256\n")
    p.append(f"#define FFT_EPS {eps:.9g}f\n")
    p.append("#define B1_IN 48\n#define B1_OUT 32\n#define B1_K 5\n")
    p.append("#define B2_IN 32\n#define B2_OUT 32\n#define B2_K 3\n")
    p.append(f"#define FC_IN 32\n#define FC_OUT {NC}\n\n")
    p.append("static const char* const MODEL_CLASS_NAMES[MODEL_N_CLASSES] = {\n")
    for c in classes:
        p.append(f'  "{c}",\n')
    p.append("};\n\n")
    p.append("// FFT filters: (2*48=96, 129) cos/sin interleaved, no bias\n")
    p.append(emit("FFT_WEIGHT", fft_w))
    p.append("\n// block1 conv (32,48,5) BN-folded + bias\n")
    p.append(emit("B1_WEIGHT", b1_w)); p.append(emit("B1_BIAS", b1_b))
    p.append("\n// block2 conv (32,32,3) BN-folded + bias\n")
    p.append(emit("B2_WEIGHT", b2_w)); p.append(emit("B2_BIAS", b2_b))
    p.append("\n// fc (2,32) + bias\n")
    p.append(emit("FC_WEIGHT", fc_w)); p.append(emit("FC_BIAS", fc_b))
    p.append(f"\n#define NUM_TEST_SAMPLES {len(idx)}\n")
    p.append(emit("TEST_SAMPLES", sX))
    p.append("static const int TEST_TRUE_LABELS[NUM_TEST_SAMPLES] = {\n  " + ", ".join(str(int(v)) for v in sY) + "\n};\n\n")
    p.append("static const int REF_PRED_LABELS[NUM_TEST_SAMPLES] = {\n  " + ", ".join(str(int(v)) for v in preds) + "\n};\n\n")
    p.append(emit("REF_LOGITS", logits))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(p))
    print(f"== wrote {OUT} ({OUT.stat().st_size/1024:.0f} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
