"""Export the 1D binary mosquito detector to firmware/wingbeat_inference/model_weights.h.

Same architecture family as the earlier W11 student (Conv1d 8->16->24, BN folded,
GAP, FC 24->16->2), so the on-chip C++ in firmware/wingbeat_stream runs it
unchanged — only the class count differs (3 -> 2). Reuses BN folding + C-array
emission. Reference samples come from exp_audio_detector_1d/stream_test.npz.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.models.cnn_1d import CNN1D  # noqa: E402

CKPT = ROOT / "experiments" / "exp_audio_detector_1d" / "best.pt"
STREAM = ROOT / "experiments" / "exp_audio_detector_1d" / "stream_test.npz"
OUT_HEADER = ROOT / "firmware" / "wingbeat_inference" / "model_weights.h"


def fold_bn(conv, bn):
    w = conv.weight.detach().cpu().numpy()
    b = (conv.bias.detach().cpu().numpy() if conv.bias is not None
         else np.zeros(w.shape[0], np.float32))
    g = bn.weight.detach().cpu().numpy(); beta = bn.bias.detach().cpu().numpy()
    mean = bn.running_mean.detach().cpu().numpy(); var = bn.running_var.detach().cpu().numpy()
    scale = g / np.sqrt(var + bn.eps)
    return (w * scale[:, None, None]).astype(np.float32), (beta + scale*(b-mean)).astype(np.float32)


def emit(name, arr, fmt="{:.7g}f"):
    flat = arr.flatten()
    body = ",\n  ".join(", ".join(fmt.format(float(x)) for x in flat[i:i+8]) for i in range(0, len(flat), 8))
    return f"static const float {name}[{len(flat)}] = {{\n  {body}\n}};\n"


def main() -> int:
    ck = torch.load(CKPT, map_location="cpu", weights_only=False)
    kwargs = ck["kwargs"]; classes = ck["classes"]
    model = CNN1D(**kwargs).eval(); model.load_state_dict(ck["model"])
    print(f"== model: {sum(p.numel() for p in model.parameters()):,} params, classes {classes}")

    fused = [fold_bn(b.conv, b.bn) for b in model.blocks]
    fc1_w = model.fc1.weight.detach().cpu().numpy().astype(np.float32)
    fc1_b = model.fc1.bias.detach().cpu().numpy().astype(np.float32)
    fc2_w = model.fc2.weight.detach().cpu().numpy().astype(np.float32)
    fc2_b = model.fc2.bias.detach().cpu().numpy().astype(np.float32)

    z = np.load(STREAM, allow_pickle=True)
    X, y = z["X"], z["y"]
    rng = np.random.default_rng(42)
    idx = []
    for c in range(len(classes)):
        ci = np.where(y == c)[0]
        idx.extend(int(i) for i in rng.choice(ci, size=min(3, len(ci)), replace=False))
    sX = X[idx].astype(np.float32); sY = y[idx].astype(np.int64)

    with torch.no_grad():
        logits = model(torch.as_tensor(sX).unsqueeze(1)).numpy()
        probs = torch.softmax(torch.as_tensor(logits), -1).numpy()
        preds = logits.argmax(-1)
    print(f"   ref preds {preds.tolist()} vs true {sY.tolist()}")

    NC = len(classes)
    p = []
    p.append("// AUTO-GENERATED by scripts/export_detector_1d_for_esp32.py — do not edit\n#pragma once\n\n")
    p.append("// 1D binary mosquito detector — Conv1d 8->16->24 (BN folded) -> GAP -> FC(24,16)+ReLU -> FC(16,2)\n\n")
    p.append(f"#define MODEL_INPUT_LEN {sX.shape[1]}\n#define MODEL_N_CLASSES {NC}\n")
    p.append("#define MODEL_BLOCK0_IN_CH 1\n#define MODEL_BLOCK0_OUT_CH 8\n#define MODEL_BLOCK0_KERNEL 7\n")
    p.append("#define MODEL_BLOCK1_IN_CH 8\n#define MODEL_BLOCK1_OUT_CH 16\n#define MODEL_BLOCK1_KERNEL 5\n")
    p.append("#define MODEL_BLOCK2_IN_CH 16\n#define MODEL_BLOCK2_OUT_CH 24\n#define MODEL_BLOCK2_KERNEL 3\n")
    p.append(f"#define MODEL_FC1_IN 24\n#define MODEL_FC1_OUT 16\n#define MODEL_FC2_IN 16\n#define MODEL_FC2_OUT {NC}\n\n")
    p.append("static const char* const MODEL_CLASS_NAMES[MODEL_N_CLASSES] = {\n")
    for c in classes:
        p.append(f'  "{c}",\n')
    p.append("};\n\n")
    for i, (w, b) in enumerate(fused):
        p.append(f"// block {i}: conv (out={w.shape[0]}, in={w.shape[1]}, k={w.shape[2]})\n")
        p.append(emit(f"BLOCK{i}_WEIGHT", w)); p.append(emit(f"BLOCK{i}_BIAS", b)); p.append("\n")
    p.append("// fc1 (out=16,in=24)\n"); p.append(emit("FC1_WEIGHT", fc1_w)); p.append(emit("FC1_BIAS", fc1_b))
    p.append(f"\n// fc2 (out={NC},in=16)\n"); p.append(emit("FC2_WEIGHT", fc2_w)); p.append(emit("FC2_BIAS", fc2_b))
    p.append("\n")
    p.append(f"#define NUM_TEST_SAMPLES {len(idx)}\n")
    p.append(emit("TEST_SAMPLES", sX))
    p.append("static const int TEST_TRUE_LABELS[NUM_TEST_SAMPLES] = {\n  " + ", ".join(str(int(v)) for v in sY) + "\n};\n\n")
    p.append("static const int REF_PRED_LABELS[NUM_TEST_SAMPLES] = {\n  " + ", ".join(str(int(v)) for v in preds) + "\n};\n\n")
    p.append(emit("REF_LOGITS", logits)); p.append(emit("REF_PROBS", probs))

    OUT_HEADER.write_text("".join(p))
    print(f"== wrote {OUT_HEADER} ({OUT_HEADER.stat().st_size/1024:.0f} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
